export const TextStrings = {
  TrackBookAndSubmit: 'Track, Book & Submit',
  TrackYourActivity:
    'Track your activities, document your progress in a book, and submit your achievements for review.',
  GrowthAndDevelopment: 'Growth & Development',
  ExpandAndEvolveThrough:
    'Expand and evolve through ongoing learning, personal reflection, and application of new skills and knowledge.',
  GetSmartNotifications: 'Get Smart Notifications',
  ReceiveIntelligentAlerts:
    'Receive intelligent alerts tailored to your preferences and needs, ensuring you stay informed and connected efficiently.',
  of: 'of',
  SignIn: 'Sign In',
  WelcomePleaseSignInToAccess:
    'Welcome! Please sign in to access personalised features and a seamless experience.',
  SignUp: 'Sign Up',
  JoinUsTodayToDiscover:
    'Join us today to discover new possibilities and customise your personal experience with Vinea.',
  EmailWithDeash: 'E-mail',
  Password: 'Password',
  FullName: 'Full Name',
  NPI: 'NPI',
  EmailAddress: 'Email Address',
  EnterOTP: 'Enter OTP',
  EnterPin: 'Enter Pin',
  Proceed: 'Proceed',
  NewPassword: 'New Password',
  ConfirmPassword: 'Confirm Password',
  CreateAnAccount: 'Create an account',
  AlreadyHaveAnAccount: 'Already have an account?',
  DontHaveAnAccount: 'Don’t have an account?',
  ForgotPassword: 'Forgot Password?',
  PleaseEnterValidEmail: 'Please enter a valid email',
  PleaseEnterValidPassword: 'Please enter a valid password',
  PleaseEnterValidConfirmPassword: 'Please enter a valid confirm password',
  PleaseEnterCorrectEmail: 'Please enter correct email',
  PasswordIsToSort: 'Password is to sort',
  PleaseEnterFullName: 'Please enter a full name',
  PleaseEnterNPI: 'Please enter NPI number',
  PasswordNotMatched: 'Password not matched',
  InvalidToken: 'Invalid token',
  Unauthorized: 'Unauthorized',
  YouAreBlockedByAdmin: 'Your block by admin',
  HaventReceivedTheCode: "Haven't received the code?",
  SendItAgain: 'Send it again.',
  Continue: 'Continue',
  OTPExpiredRequestAgain: "you'r OTP is expired, please request again",
  CreateNewPassword: 'Create New Password',
  ResetPassword: 'Reset Password',
  Credits: 'Credits',
  Connections: 'Connections',
  Welcome: 'Welcome',
  Comments: 'Comments',
  TypeMessage: 'Type a message',
  Alert: 'Alert',
  RequiredCourses: 'Required Courses',
  CMECredits: 'CME Credits',
  hours: 'hours',
  BookAndRegister: 'Book & Register',
  Settings: 'Settings',
  AccessViaBiometrics: 'Access via biometrics',
  CustomizeResults: 'Customise Results',
};

export default TextStrings;
